name: Clojure CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.727'

    - name: Run tests
      run: clojure -M:test

    - name: Package jar
      run: clojure -M:depstar -m hf.depstar.jar tako.jar

    - name: Publish
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USER }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASS }}
      run: clojure -M:deploy
